# We need sudo do docker on travis
sudo: required

# language is required by travis, but not used in this build.
# so we set it to ruby for no real reason
language: ruby

services:
  - docker

install:
  - echo "No install step yet"

script:
  - echo "We don't need no tests."

after_success:
  - docker --version
  - pip install --user awscli
  - export PATH=$PATH:/.local/bin
  - eval $(aws ecr get-login --no-include-email --region us-west-2) # Need AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY in the environment
  - docker build -t hubot-ash .
  - docker tag hubot-ash:latest 583493077616.dkr.ecr.us-west-2.amazonaws.com/hubot-ash:latest
  - docker push 583493077616.dkr.ecr.us-west-2.amazonaws.com/hubot-ash:latest
